### ISSUE TITLE
python name clash with py3exiv2

### ISSUE THREAD

**Issue by cryptomilk** [LeoHsiao1/pyexiv2#78]
Hi,

you created a module which provides `exiv2` for python with the same name as [py3exiv2](https://pypi.org/project/py3exiv2/). So this creates a conflict.

py3exiv2 is what distributions are packaging!

https://build.opensuse.org/package/show/devel:languages:python/python-exiv2
https://src.fedoraproject.org/rpms/python3-exiv2
https://aur.archlinux.org/packages/python-exiv2/

I would suggest that you rename it, in case you want that distributions package your module.

**Comment by LeoHsiao1** [comment]
Hi!
When I started this project two years ago, I couldn't find a project named pyexiv2 on pypi.org, so I used this name.
Since changing the project name will affect all users, I'd rather put up with the problem.
I've just added documentation that describes the differences between pyexiv2 and py3exiv2.
